### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by adhoc-transbot** [ingadhoc/odoo-public-administration#218]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] public_budget
- [ ] public_budget_subscription
- [ ] public_budget_tax_settlement
- [ ] sipreco_payment_line
- [ ] sipreco_position_helper
- [ ] sipreco_project
- [ ] sipreco_purchase
- [ ] sipreco_subsidy_management
