### ISSUE TITLE
Migration to version 13.0

### ISSUE THREAD

**Issue by jjscarafia** [ingadhoc/odoo-public-administration#350]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0

# Modules to migrate

- [ ] sipreco_subsidy_management
- [ ] sipreco_payment_line
- [ ] sipreco_project
- [ ] public_budget
- [ ] sipreco_purchase
- [ ] public_budget_tax_settlement
- [ ] public_budget_subscription
- [ ] sipreco_position_helper
